Parameters:
  KeyName:
    Description: Name of the existing EC2 KeyPair to enable ssh access into the server
    Type: AWS::EC2::KeyPair::KeyName
  MyIp:
    Description: "IP address to be added in the security group for access"
    Type: String
Mappings:
  RegionMap:
    us-west-2:
      AMI: ami-0f2176987ee50226e
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.nano
      UserData:
        !Base64 |
          #!/bin/bash
          yum update -y
          yum install httpd -y
          service httpd start
      ImageId:
        Fn::FindInMap:
        - RegionMap
        - !Ref AWS::Region
        - AMI
      Tags:
        - Key: "Name"
          Value: !Join
            - ""
            - - "EC2 Instance for "
              - !Ref AWS::Region
        - Key: "CreatedBy"
          Value: !Ref AWS::AccountId
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref MySecurityGroup
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Join
            - ""
            - - !Ref MyIp
              - "/32"
Outputs:
  ServerDNS:
    Value: !GetAtt
      - Ec2Instance
      - PublicDnsName